title: Olubiyi Akintade # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This e-Portfolio is based on my work on MSc Data Science, University of Essex. 
  I have previously carried out research works on the development of cyber-physical 
  systems and IoT applications. This essentially means that I have mostly worked at 
  the data generation stage of the data management lifecycle. 
  <br>
  <a href="https://scholar.google.com/citations?user=9cy2hdYAAAAJ&hl=en">View My Publications</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
